service: serverless-user-auth

provider:
  name: aws
  runtime: nodejs14.x

functions:
  auth:
    handler: src/lambda.handler
    events:
      - http:
          path: register
          method: post  # Registration endpoint for user authentication
      - http:
          path: login
          method: post     # Login endpoint for user authentication

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1  # Read capacity units for DynamoDB table
          WriteCapacityUnits: 1  # Write capacity units for DynamoDB table